src/main/java/cn/gzjp/modules/gen/entity/GenCategory.java
/**
 * Copyright &copy; 2012-2016 <a href="https://github.com/thinkgem/jeesite">JeeSite</a> All rights reserved.
 */
package cn.gzjp.modules.gen.entity;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import cn.gzjp.modules.sys.entity.Dict;


/**
 * 生成方案Entity
 * @author ThinkGem
 * @version 2013-10-15
 */
@XmlRootElement(name="category")
public class GenCategory extends Dict {
	
	private static final long serialVersionUID = 1L;
	private List<String> template;			// 主表模板
	private List<String> childTableTemplate;// 子表模板
	
	public static String CATEGORY_REF = "category-ref:";

	public GenCategory() {
		super();
	}

	@XmlElement(name = "template")
	public List<String> getTemplate() {
		return template;
	}

	public void setTemplate(List<String> template) {
		this.template = template;
	}
	
	@XmlElementWrapper(name = "childTable")
	@XmlElement(name = "template")
	public List<String> getChildTableTemplate() {
		return childTableTemplate;
	}

	public void setChildTableTemplate(List<String> childTableTemplate) {
		this.childTableTemplate = childTableTemplate;
	}
	
}

src/main/java/cn/gzjp/modules/gen/entity/GenConfig.java
/**
 * Copyright &copy; 2012-2016 <a href="https://github.com/thinkgem/jeesite">JeeSite</a> All rights reserved.
 */
package cn.gzjp.modules.gen.entity;

import java.io.Serializable;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import cn.gzjp.modules.sys.entity.Dict;


/**
 * 生成方案Entity
 * @author ThinkGem
 * @version 2013-10-15
 */
@XmlRootElement(name="config")
public class GenConfig implements Serializable {
	
	private static final long serialVersionUID = 1L;
	private List<GenCategory> categoryList;	// 代码模板分类
	private List<Dict> javaTypeList;		// Java类型
	private List<Dict> queryTypeList;		// 查询类型
	private List<Dict> showTypeList;		// 显示类型

	public GenConfig() {
		super();
	}

	@XmlElementWrapper(name = "category")
	@XmlElement(name = "category")
	public List<GenCategory> getCategoryList() {
		return categoryList;
	}

	public void setCategoryList(List<GenCategory> categoryList) {
		this.categoryList = categoryList;
	}

	@XmlElementWrapper(name = "javaType")
	@XmlElement(name = "dict")
	public List<Dict> getJavaTypeList() {
		return javaTypeList;
	}

	public void setJavaTypeList(List<Dict> javaTypeList) {
		this.javaTypeList = javaTypeList;
	}

	@XmlElementWrapper(name = "queryType")
	@XmlElement(name = "dict")
	public List<Dict> getQueryTypeList() {
		return queryTypeList;
	}

	public void setQueryTypeList(List<Dict> queryTypeList) {
		this.queryTypeList = queryTypeList;
	}

	@XmlElementWrapper(name = "showType")
	@XmlElement(name = "dict")
	public List<Dict> getShowTypeList() {
		return showTypeList;
	}

	public void setShowTypeList(List<Dict> showTypeList) {
		this.showTypeList = showTypeList;
	}
	
}

src/main/java/cn/gzjp/modules/gen/entity/GenScheme.java
/**
 * Copyright &copy; 2012-2016 <a href="https://github.com/thinkgem/jeesite">JeeSite</a> All rights reserved.
 */
package cn.gzjp.modules.gen.entity;

import org.hibernate.validator.constraints.Length;

import cn.gzjp.common.persistence.DataEntity;

/**
 * 生成方案Entity
 * @author ThinkGem
 * @version 2013-10-15
 */
public class GenScheme extends DataEntity<GenScheme> {
	
	private static final long serialVersionUID = 1L;
	private String name; 	// 名称
	private String category;		// 分类
	private String packageName;		// 生成包路径
	private String moduleName;		// 生成模块名
	private String subModuleName;		// 生成子模块名
	private String functionName;		// 生成功能名
	private String functionNameSimple;		// 生成功能名（简写）
	private String functionAuthor;		// 生成功能作者
	private GenTable genTable;		// 业务表名
	
	private String flag; 	// 0：保存方案； 1：保存方案并生成代码
	
	private Boolean replaceFile;	// 是否替换现有文件    0：不替换；1：替换文件

	public GenScheme() {
		super();
	}

	public GenScheme(String id){
		super(id);
	}
	
	@Length(min=1, max=200)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPackageName() {
		return packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public String getSubModuleName() {
		return subModuleName;
	}

	public void setSubModuleName(String subModuleName) {
		this.subModuleName = subModuleName;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getFunctionName() {
		return functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getFunctionNameSimple() {
		return functionNameSimple;
	}

	public void setFunctionNameSimple(String functionNameSimple) {
		this.functionNameSimple = functionNameSimple;
	}

	public String getFunctionAuthor() {
		return functionAuthor;
	}

	public void setFunctionAuthor(String functionAuthor) {
		this.functionAuthor = functionAuthor;
	}

	public GenTable getGenTable() {
		return genTable;
	}

	public void setGenTable(GenTable genTable) {
		this.genTable = genTable;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Boolean getReplaceFile() {
		return replaceFile;
	}

	public void setReplaceFile(Boolean replaceFile) {
		this.replaceFile = replaceFile;
	}
	
}

src/main/java/cn/gzjp/modules/gen/entity/GenTable.java
/**
 * Copyright &copy; 2012-2016 <a href="https://github.com/thinkgem/jeesite">JeeSite</a> All rights reserved.
 */
package cn.gzjp.modules.gen.entity;

import java.util.List;

import org.hibernate.validator.constraints.Length;

import com.google.common.collect.Lists;
import cn.gzjp.common.persistence.DataEntity;
import cn.gzjp.common.utils.StringUtils;

/**
 * 业务表Entity
 * @author ThinkGem
 * @version 2013-10-15
 */
public class GenTable extends DataEntity<GenTable> {
	
	private static final long serialVersionUID = 1L;
	private String name; 	// 名称
	private String comments;		// 描述
	private String className;		// 实体类名称
	private String parentTable;		// 关联父表
	private String parentTableFk;		// 关联父表外键

	private List<GenTableColumn> columnList = Lists.newArrayList();	// 表列

	private String nameLike; 	// 按名称模糊查询
	
	private List<String> pkList; // 当前表主键列表
	
	private GenTable parent;	// 父表对象
	private List<GenTable> childList = Lists.newArrayList();	// 子表列表
	
	public GenTable() {
		super();
	}

	public GenTable(String id){
		super(id);
	}

	@Length(min=1, max=200)
	public String getName() {
		return StringUtils.lowerCase(name);
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getParentTable() {
		return StringUtils.lowerCase(parentTable);
	}

	public void setParentTable(String parentTable) {
		this.parentTable = parentTable;
	}

	public String getParentTableFk() {
		return StringUtils.lowerCase(parentTableFk);
	}

	public void setParentTableFk(String parentTableFk) {
		this.parentTableFk = parentTableFk;
	}

	public List<String> getPkList() {
		return pkList;
	}

	public void setPkList(List<String> pkList) {
		this.pkList = pkList;
	}

	public String getNameLike() {
		return nameLike;
	}

	public void setNameLike(String nameLike) {
		this.nameLike = nameLike;
	}

	public GenTable getParent() {
		return parent;
	}

	public void setParent(GenTable parent) {
		this.parent = parent;
	}

	public List<GenTableColumn> getColumnList() {
		return columnList;
	}

	public void setColumnList(List<GenTableColumn> columnList) {
		this.columnList = columnList;
	}

	public List<GenTable> getChildList() {
		return childList;
	}

	public void setChildList(List<GenTable> childList) {
		this.childList = childList;
	}
	
	/**
	 * 获取列名和说明
	 * @return
	 */
	public String getNameAndComments() {
		return getName() + (comments == null ? "" : "  :  " + comments);
	}

	/**
	 * 获取导入依赖包字符串
	 * @return
	 */
	public List<String> getImportList(){
		List<String> importList = Lists.newArrayList(); // 引用列表
		for (GenTableColumn column : getColumnList()){
			if (column.getIsNotBaseField() || ("1".equals(column.getIsQuery()) && "between".equals(column.getQueryType())
							&& ("createDate".equals(column.getSimpleJavaField()) || "updateDate".equals(column.getSimpleJavaField())))){
				// 导入类型依赖包， 如果类型中包含“.”，则需要导入引用。
				if (StringUtils.indexOf(column.getJavaType(), ".") != -1 && !importList.contains(column.getJavaType())){
					importList.add(column.getJavaType());
				}
			}
			if (column.getIsNotBaseField()){
				// 导入JSR303、Json等依赖包
				for (String ann : column.getAnnotationList()){
					if (!importList.contains(StringUtils.substringBeforeLast(ann, "("))){
						importList.add(StringUtils.substringBeforeLast(ann, "("));
					}
				}
			}
		}
		// 如果有子表，则需要导入List相关引用
		if (getChildList() != null && getChildList().size() > 0){
			if (!importList.contains("java.util.List")){
				importList.add("java.util.List");
			}
			if (!importList.contains("com.google.common.collect.Lists")){
				importList.add("com.google.common.collect.Lists");
			}
		}
		return importList;
	}
	
	/**
	 * 是否存在父类
	 * @return
	 */
	public Boolean getParentExists(){
		return parent != null && StringUtils.isNotBlank(parentTable) && StringUtils.isNotBlank(parentTableFk);
	}

	/**
	 * 是否存在create_date列
	 * @return
	 */
	public Boolean getCreateDateExists(){
		for (GenTableColumn c : columnList){
			if ("create_date".equals(c.getName())){
				return true;
			}
		}
		return false;
	}
	
	/**
	 * 是否存在update_date列
	 * @return
	 */
	public Boolean getUpdateDateExists(){
		for (GenTableColumn c : columnList){
			if ("update_date".equals(c.getName())){
				return true;
			}
		}
		return false;
	}

	/**
	 * 是否存在del_flag列
	 * @return
	 */
	public Boolean getDelFlagExists(){
		for (GenTableColumn c : columnList){
			if ("del_flag".equals(c.getName())){
				return true;
			}
		}
		return false;
	}
}

src/main/java/cn/gzjp/modules/gen/entity/GenTemplate.java
/**
 * Copyright &copy; 2012-2016 <a href="https://github.com/thinkgem/jeesite">JeeSite</a> All rights reserved.
 */
package cn.gzjp.modules.gen.entity;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.Length;

import com.google.common.collect.Lists;
import cn.gzjp.common.persistence.DataEntity;
import cn.gzjp.common.utils.StringUtils;

/**
 * 生成方案Entity
 * @author ThinkGem
 * @version 2013-10-15
 */
@XmlRootElement(name="template")
public class GenTemplate extends DataEntity<GenTemplate> {
	
	private static final long serialVersionUID = 1L;
	private String name; 	// 名称
	private String category;		// 分类
	private String filePath;		// 生成文件路径
	private String fileName;		// 文件名
	private String content;		// 内容

	public GenTemplate() {
		super();
	}

	public GenTemplate(String id){
		super(id);
	}
	
	@Length(min=1, max=200)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}
	
	@XmlTransient
	public List<String> getCategoryList() {
		if (category == null){
			return Lists.newArrayList();
		}else{
			return Lists.newArrayList(StringUtils.split(category, ","));
		}
	}

	public void setCategoryList(List<String> categoryList) {
		if (categoryList == null){
			this.category = "";
		}else{
			this.category = ","+StringUtils.join(categoryList, ",") + ",";
		}
	}
	
}

src/main/java/cn/gzjp/modules/portal/entity/Banner.java
package cn.gzjp.modules.portal.entity;

import org.hibernate.validator.constraints.Length;

import cn.gzjp.common.persistence.DataEntity;
import cn.gzjp.common.utils.excel.annotation.ExcelField;

/**
 * 轮播图Entity
 * @author zengcp
 * @version 2017-08-22
 */
public class Banner extends DataEntity<Banner> {
	
	private static final long serialVersionUID = 1L;
	private String pic;		// 图片地址
	private int sort;		// 顺序
	private String url;		// 链接地址
	private String type;// 0 banner轮播 1企业价值观
	
	private String w1;
	private String w2;
	

	
	public Banner() {
		super();
	}

	public Banner(String id){
		super(id);
	}

	@Length(min=0, max=256, message="图片地址长度必须介于 0 和 256 之间")
	@ExcelField(title="图片地址", align=2, sort=1)
	public String getPic() {
		return pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}
	
	public int getSort() {
		return sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}
	
	@Length(min=0, max=256, message="链接地址长度必须介于 0 和 256 之间")
	@ExcelField(title="链接地址", align=2, sort=4)
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getW1() {
		return w1;
	}

	public void setW1(String w1) {
		this.w1 = w1;
	}

	public String getW2() {
		return w2;
	}

	public void setW2(String w2) {
		this.w2 = w2;
	}

}

src/main/java/cn/gzjp/modules/portal/entity/Item.java
package cn.gzjp.modules.portal.entity;

import cn.gzjp.common.persistence.DataEntity;
import cn.gzjp.common.utils.excel.annotation.ExcelField;
import cn.gzjp.modules.portal.entity.vo.DownLoadVo;
import cn.gzjp.modules.sys.utils.DictUtils;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.xiaoleilu.hutool.util.StrUtil;
import org.hibernate.validator.constraints.Length;

import java.util.List;

/**
 * 新闻类型Entity
 * @author zengcp
 * @version 2017-08-17
 */
public class Item extends DataEntity<Item> {

	private static final long serialVersionUID = 1L;
	private String type;

	private String name;		// 名称
	private Item parent;		// 上级id
	private Integer sort;		// 排序
	private String parentIds;		// 所有父级编号
	private List<Item> children;	// 子菜单

	private String content;
	private Integer itemId; //栏目编号

	private Integer parentItemId;

	private String isShow; 	//是否在菜单中显示（1：显示；0：不显示）



	public Item() {
		super();
	}

	public Item(String id){
		super(id);
	}

	@Length(min=0, max=64, message="名称长度必须介于 0 和 64 之间")
	@ExcelField(title="名称", align=2, sort=1)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	@JsonBackReference
	@ExcelField(title="上级id", align=2, sort=3)
	public Item getParent() {
		return parent;
	}

	public void setParent(Item parent) {
		this.parent = parent;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getParentIds() {
		return parentIds;
	}

	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	public List<Item> getChildren() {
		return children;
	}

	public void setChildren(List<Item> children) {
		this.children = children;
	}
	public String getParentId() {
		return parent != null && parent.getId() != null ? parent.getId() : "0";
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getItemId() {
		return itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public String getUrl(){
		if(StrUtil.isNotBlank(this.getType())){
			String url = this.getType().replace("_id",this.getItemId()+"");
			return url;
		}
		return "";

	}


	public String getIsNewsList(){
		if("news_id.html".equals(this.getType())||"service_id.html".equals(this.getType())||"brand_id.html".equals(this.getType())||"activity_id.html".equals(this.getType())){
			return "news";
		}

		return "";
	}




	public String getPageName(){
		return DictUtils.getDictLabel(this.getType(),"item_type","");
	}

	public Integer getParentItemId() {
		return parentItemId;
	}

	public void setParentItemId(Integer parentItemId) {
		this.parentItemId = parentItemId;
	}

	public String getIsShow() {
		return isShow;
	}

	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}
}

src/main/java/cn/gzjp/modules/portal/entity/ProductStyle.java
package cn.gzjp.modules.portal.entity;

import cn.gzjp.common.persistence.DataEntity;

/**
 * @Author zengcp
 * @Date 2018/10/13
 */
public class ProductStyle extends DataEntity<ProductStyle> {

    private long productId;

    private String name;

    public long getProductId() {
        return productId;
    }

    public void setProductId(long productId) {
        this.productId = productId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/webapp/WEB-INF/views/modules/portal/itemList.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp"%>
<html>
<head>
	<title>栏目管理</title>
	<meta name="decorator" content="default"/>
	<%@include file="/WEB-INF/views/include/treetable.jsp" %>
	<script src="${ctxStatic}/common/contabs.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			var tpl = $("#treeTableTpl").html().replace(/(\/\/\<!\-\-)|(\/\/\-\->)/g,"");
			var data = ${fns:toJson(list)}, ids = [], rootIds = [];
			for (var i=0; i<data.length; i++){
				ids.push(data[i].id);
			}
			ids = ',' + ids.join(',') + ',';
			for (var i=0; i<data.length; i++){
				if (ids.indexOf(','+data[i].parentId+',') == -1){
					if ((','+rootIds.join(',')+',').indexOf(','+data[i].parentId+',') == -1){
						rootIds.push(data[i].parentId);
					}
				}
			}
			for (var i=0; i<rootIds.length; i++){
				addRow("#treeTableList", tpl, data, rootIds[i], true);
			}
			$("#treeTable").treeTable({expandLevel : 2});
			$('.zml0').show();
            $('.d70a114351e149a387acbc1bcd7aba35').show();
           // $('.d19fcbf3ca37431dbfc1c6dcd2059d43').show();

            $('.news').show();


            $('.简介页').show();
		});
		function addRow(list, tpl, data, pid, root){
			for (var i=0; i<data.length; i++){
				var row = data[i];
				if ((${fns:jsGetVal('row.parentId')}) == pid){
					$(list).append(Mustache.render(tpl, {
						dict: {
							type: getDictLabel(${fns:toJson(fns:getDictList('wx_menu_type'))}, row.type),
						blank123:0}, pid: (root?0:pid), row: row
					}));
					addRow(list, tpl, data, row.id);
				}
			}
		}
		
		
	</script>
</head>
<body class="gray-bg">
	<div class="wrapper wrapper-content">
	<div class="ibox">
	
    <div class="ibox-content">
	<sys:message content="${message}"/>


	
	<!-- 工具栏-->
	<div class="row">
	<div class="col-sm-12">
		<div class="pull-left">
				<table:addRow url="${ctx}/portal/item/form?type=${type}" title="栏目管理" width="550px" height="380px" label="新增栏目"></table:addRow>

			<button type="button" onclick="createHomeHtml()"  class="btn btn-primary btn-xs">生成首页html</button>
			<button type="button" onclick="createProfileHtml()"  class="btn btn-primary btn-xs">生成简介页html</button>
			<button type="button" onclick="createProductHtml()"  class="btn btn-primary btn-xs">生成全系产品html</button>

			<button type="button" onclick="createBrandHtml()"  class="btn btn-primary btn-xs">生成品牌相关html</button>
			<button type="button" onclick="createActivityHtml()"  class="btn btn-primary btn-xs">生成最新活动html</button>
			<button type="button" onclick="createNewsHtml()"  class="btn btn-primary btn-xs">新闻动态html</button>

			<button type="button" onclick="createServiceHtml()"  class="btn btn-primary btn-xs">服务中心html</button>
		</div>
	</div>
	</div>

	<table id="treeTable" class="table table-striped table-bordered table-hover table-condensed dataTables-example dataTable">
		<thead>
			<tr>
				<th>栏目名称</th>
				<th>栏目编号</th>
				<th>页面</th>
				<th>url</th>
				<th>排序</th>
				<th width="35%">操作</th>
			</tr>
		</thead>
		<tbody id="treeTableList"></tbody>
	</table>
	<script type="text/template" id="treeTableTpl">
		<tr id="{{row.id}}" pId="{{pid}}">
			<td>
				{{row.name}}
			</td>
			<td>
				{{row.itemId}}
			</td>
			<td>
				{{row.pageName}}
			</td>
			<td>
				{{row.url}}
			</td>
			<td>
				{{row.sort}}
			</td>
			<td>
   				<a href="#" onclick="openDialog('修改', '${ctx}/portal/item/form?id={{row.id}}&type={{row.type}}&parentItemId={{row.parentItemId}}','550px', '380px')" class="btn btn-success btn-xs" ><i class="fa fa-edit"></i> 修改</a>
				<a href="${ctx}/portal/item/delete?id={{row.id}}" onclick="return confirmx('确认要删除该栏目吗？', this.href)" class="btn btn-danger btn-xs" ><i class="fa fa-trash"></i> 删除</a>
			    <span class="zml{{row.parentId}}" style="display:none" ><a href="#" onclick="openDialog('{{row.name}}_新增子栏目', '${ctx}/portal/item/form?parent.id={{row.id}}&type={{row.type}}&parentItemId={{row.itemId}}','550px', '380px')" class="btn btn-warning btn-xs" ><i class="fa fa-plus"></i> 新增子栏目</a>
                </span>
				<span class="{{row.parentId}}" style="display:none" ><a href="#" onclick="openDialog('{{row.name}}_新增子栏目', '${ctx}/portal/item/form?parent.id={{row.id}}&type={{row.type}}&parentItemId={{row.itemId}}','550px', '380px')" class="btn btn-warning btn-xs" ><i class="fa fa-plus"></i> 新增子栏目</a>
                </span>
				<span class="{{row.id}}" style="display:none" ><a href="#" onclick="openDialog('{{row.name}}_新闻类型', '${ctx}/portal/item/form?parent.id={{row.id}}&type={{row.type}}&parentItemId={{row.itemId}}','550px', '380px')" class="btn btn-warning btn-xs" ><i class="fa fa-plus"></i> 新增子栏目</a>
                </span>
				<span class="{{row.pageName}}" style="display:none" ><a href="#" onclick="openDialog('{{row.name}}_编辑页面内容', '${ctx}/portal/item/contentForm?id={{row.id}}&type={{row.type}}','100%', '100%')" ><i class="fa fa-plus"></i> 编辑内容</a>
                </span>

				<span class="{{row.isNewsList}}" style="display:none" ><a  onclick="openTab('${ctx}/portal/news?itemId={{row.itemId}}&type={{row.type}}','{{row.name}}',false)"  ><i class="fa fa-plus"></i> 编辑内容</a>
                </span>

			</td>
		</tr>
	</script>

	<script>
            function createHomeHtml(){
                layer.confirm('确认生成首页html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/home',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }

            function createProfileHtml(){
                layer.confirm('确认生成简介页html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/profile',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }

            function createProductHtml(){
                layer.confirm('确认生成html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/product',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }

            function createBrandHtml(){
                layer.confirm('确认生成html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/brand',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }
            function createActivityHtml(){
                layer.confirm('确认生成html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/activity',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }

            function createNewsHtml(){
                layer.confirm('确认生成html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/news',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }

            function createServiceHtml(){
                layer.confirm('确认生成html?',{icon: 3, title:'系统提示'},   function(){
                    $.get('${ctx}/html/create/service',function(result){layer.msg('操作成功', {time: 2000}); search(); });
                });
            }

		</script>
</body>
</html>